name: Build IDS static data

on:
  workflow_dispatch: {}
  schedule:
    - cron: "12 3 * * *"  # daily at 03:12 UTC

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Build IDS JSON (Source 6 + WLD)
        run: |
          mkdir -p scripts data
          python scripts/fetch_ids.py

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(data): update IDS static JSON (source=6, WLD)"
          file_pattern: data/*.json
